// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5NhIRdfGNOvFU_tS7D_Y1kCWRPFW4XUU',
    appId: '1:22185381347:web:de444c3a3b4a844ac5e4d6',
    messagingSenderId: '22185381347',
    projectId: 'flutter-login-study-74d93',
    authDomain: 'flutter-login-study-74d93.firebaseapp.com',
    storageBucket: 'flutter-login-study-74d93.firebasestorage.app',
    measurementId: 'G-NRWP9QMD0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVL9zOVpXu4uRTaicsJTWLy8IxFKgcje0',
    appId: '1:22185381347:android:9974a88a64f4b581c5e4d6',
    messagingSenderId: '22185381347',
    projectId: 'flutter-login-study-74d93',
    storageBucket: 'flutter-login-study-74d93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpuTu9n5EkLxtRte82X2kigk-F3GXMdTs',
    appId: '1:22185381347:ios:6074349ead48d378c5e4d6',
    messagingSenderId: '22185381347',
    projectId: 'flutter-login-study-74d93',
    storageBucket: 'flutter-login-study-74d93.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpuTu9n5EkLxtRte82X2kigk-F3GXMdTs',
    appId: '1:22185381347:ios:6074349ead48d378c5e4d6',
    messagingSenderId: '22185381347',
    projectId: 'flutter-login-study-74d93',
    storageBucket: 'flutter-login-study-74d93.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5NhIRdfGNOvFU_tS7D_Y1kCWRPFW4XUU',
    appId: '1:22185381347:web:f0a5354056450ab6c5e4d6',
    messagingSenderId: '22185381347',
    projectId: 'flutter-login-study-74d93',
    authDomain: 'flutter-login-study-74d93.firebaseapp.com',
    storageBucket: 'flutter-login-study-74d93.firebasestorage.app',
    measurementId: 'G-80B18W4YBZ',
  );
}
